spring.application.name=WissendBackend


server.port=1000

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.password=181317
spring.datasource.username=postgres

jwt.secret=mFxrW5hlL9oxA7yjZ3voH2epT1rbD0yL7rkV6jeU9pfF4cQ0hpD8auM1fqZ3zK7nvF8mpC0sfJyj4baS3etX1unZ2oqF7haD3ktB9yrA4goJ2ujT0dpL1xM6
jwt.expiration=86400000